// daftar_lagu.js
window.playlistMap = {
  happy: [
    {
      title: "Kamulah Satu-satunya",
      artist: "Dewa 19",
      album: "Pandawa Lima",
      url: "https://music.youtube.com/watch?v=HjC43pC7CKo&si=fS4dDk99RtV7_iak",
    },
    {
      title: "Bebas",
      artist: "Iwa K",
      album: "Bebas",
      url: "https://music.youtube.com/watch?v=r-T9JrWL63E&si=xZXb9_y5VB3Vz18n",
    },
    {
      title: "Resah",
      artist: "Payung Teduh",
      album: "Payung Teduh",
      url: "https://music.youtube.com/watch?v=jWq8hHCOJkg&si=uysvoeKjaD1m3aeE",
    },
    {
      title: "Melompat Lebih Tinggi",
      artist: "Sheila On 7",
      album: "07 Des",
      url: "https://music.youtube.com/watch?v=-e_VUdAXZXY&si=wC5yUepztBA6kRaB",
    },
    {
      title: "Happy",
      artist: "Pharrell Williams",
      album: "G I R L",
      url: "https://music.youtube.com/watch?v=y6Sxv-sUYtM",
    },
    {
      title: "Sugar",
      artist: "Maroon 5",
      album: "V",
      url: "https://music.youtube.com/watch?v=09R8_2nJtjg",
    },
    {
      title: "Can't Stop The Feeling!",
      artist: "Justin Timberlake",
      album: "Trolls (Original Motion Picture Soundtrack)",
      url: "https://music.youtube.com/watch?v=ru0K8uYEZWw",
    },
    {
      title: "Walking on Sunshine",
      artist: "Katrina & The Waves",
      album: "Walking on Sunshine",
      url: "https://music.youtube.com/watch?v=iPUmE-tne5U",
    },
    {
      title: "Uptown Funk",
      artist: "Mark Ronson ft. Bruno Mars",
      album: "Uptown Special",
      url: "https://music.youtube.com/watch?v=OPf0YbXqDm0",
    },
    {
      title: "On Top of the World",
      artist: "Imagine Dragons",
      album: "Night Visions",
      url: "https://music.youtube.com/watch?v=w5tWYmIOWGk",
    },
    {
      title: "Best Day of My Life",
      artist: "American Authors",
      album: "Oh, What a Life",
      url: "https://music.youtube.com/watch?v=Y66j_BUCBMY",
    },
    {
      title: "Good Time",
      artist: "Owl City & Carly Rae Jepsen",
      album: "The Midsummer Station",
      url: "https://music.youtube.com/watch?v=H7HmzwI67ec",
    },
    {
      title: "Firework",
      artist: "Katy Perry",
      album: "Teenage Dream",
      url: "https://music.youtube.com/watch?v=QGJuMBdaqIw",
    },
    ],
  sad: [
    {
      title: "Rumah ke Rumah",
      artist: "Hindia",
      album: "Menari Dengan Bayangan",
      url: "https://music.youtube.com/watch?v=xTQvdE1oOaw&si=g8lU1C9KuGPTqANf",
    },
    {
      title: "Sampai Jadi Debu",
      artist: "Banda Neira",
      album: "Yang Patah Tumbuh",
      url: "https://music.youtube.com/watch?v=6PMHUmM_hP0&si=4sb2nNFCIhMLkVgL",
    },
    {
      title: "Dan Hilang",
      artist: "Peterpan",
      album: "OST Alexandria",
      url: "https://music.youtube.com/watch?v=-tpaCR7N_Lk&si=nWrowS5gIyZF1X1F",
    },
    {
      title: "Resah",
      artist: "Payung Teduh",
      album: "Payung Teduh",
      url: "https://music.youtube.com/watch?v=jWq8hHCOJkg&si=uysvoeKjaD1m3aeE",
    },
    {
      title: "Desember",
      artist: "Efek Rumah Kaca",
      album: "Efek Rumah Kaca",
      url: "https://music.youtube.com/watch?v=qQGVwOTalJw&si=fErYs2YocrAQJaL7",
    },
    {
      title: "Bendera",
      artist: "Cokelat",
      album: "Cokelat Band",
      url: "https://music.youtube.com/watch?v=RRau7IhLM-g&si=mrjDqvB8p5gS4Re5",
    },
     {
      title: "Duka",
      artist: "Last Child",
      album: "Our Biggest Thing Ever",
      url: "https://music.youtube.com/watch?v=lC3ZlxqDwJY",
    },
    {
      title: "Someone Like You",
      artist: "Adele",
      album: "21",
      url: "https://music.youtube.com/watch?v=hLQl3WQQoQ0",
    },
    {
      title: "Fix You",
      artist: "Coldplay",
      album: "X&Y",
      url: "https://music.youtube.com/watch?v=k4V3Mo61fJM",
    },
    {
      title: "Creep",
      artist: "Radiohead",
      album: "Pablo Honey",
      url: "https://music.youtube.com/watch?v=XFkzRNyygfk",
    },
    {
      title: "All I Want",
      artist: "Kodaline",
      album: "In a Perfect World",
      url: "https://music.youtube.com/watch?v=mtf7hC17IBM",
    },
    {
      title: "Let Her Go",
      artist: "Passenger",
      album: "All the Little Lights",
      url: "https://music.youtube.com/watch?v=RBumgq5yVrA",
    },
    {
      title: "It's Okay Not To Be Alright",
      artist: "Shane Filan",
      album: "Love Always",
      url: "https://music.youtube.com/watch?v=l4fa_j3zRHE",
    },
    {
      title: "Happier",
      artist: "Ed Sheeran",
      album: "÷ (Divide)",
      url: "https://music.youtube.com/watch?v=iWZmdoY1aTE",
    },
    {
      title: "When I Was Your Man",
      artist: "Bruno Mars",
      album: "Unorthodox Jukebox",
      url: "https://music.youtube.com/watch?v=ekzHIouo8Q4",
    },
    {
      title: "Akad",
      artist: "Payung Teduh",
      album: "Ruang Tunggu",
      url: "https://music.youtube.com/watch?v=IG0nrPxyvCk",
    },
  ],
  angry: [
    {
      title: "Bendera",
      artist: "Cokelat",
      album: "Cokelat Band",
      url: "https://music.youtube.com/watch?v=RRau7IhLM-g&si=mrjDqvB8p5gS4Re5",
    },
    {
      title: "Munafik",
      artist: "Ziva Magnolya",
      album: "Magnolya",
      url: "https://music.youtube.com/watch?v=LhcDZZULL7s&si=7zqhwHdwws9o1Rtw",
    },
    {
      title: "Posesif",
      artist: "Naif",
      album: "Jangan Terlalu",
      url: "https://music.youtube.com/watch?v=VLQS7bFQdlw&si=c-faAPjdsI-PTHiy",
    },
    {
      title: "Bring Me To Life",
      artist: "Evanescence",
      album: "Fallen",
      url: "https://music.youtube.com/watch?v=3YxaaGgTQYM",
    },
    {
      title: "In The End",
      artist: "Linkin Park",
      album: "Hybrid Theory",
      url: "https://music.youtube.com/watch?v=eVTXPUF4Oz4",
    },
    {
      title: "Smells Like Teen Spirit",
      artist: "Nirvana",
      album: "Nevermind",
      url: "https://music.youtube.com/watch?v=hTWKbfoikeg",
    },
    {
      title: "Killing In The Name",
      artist: "Rage Against The Machine",
      album: "Rage Against The Machine",
      url: "https://music.youtube.com/watch?v=bWXazVhlyxQ",
    },
    {
      title: "The Way I Am",
      artist: "Eminem",
      album: "The Marshall Mathers LP",
      url: "https://music.youtube.com/watch?v=1wYNFfgrXTI",
    },
    {
      title: "Duality",
      artist: "Slipknot",
      album: "Vol. 3: (The Subliminal Verses)",
      url: "https://music.youtube.com/watch?v=6fVE8kSM43I",
    },
    {
      title: "B.Y.O.B.",
      artist: "System Of A Down",
      album: "Mezmerize",
      url: "https://music.youtube.com/watch?v=zUzd9KyIDrM",
    },
    {
      title: "You're Gonna Go Far, Kid",
      artist: "The Offspring",
      album: "Rise and Fall, Rage and Grace",
      url: "https://music.youtube.com/watch?v=5_LxyhCJpsM",
    },
    {
      title: "Break Stuff",
      artist: "Limp Bizkit",
      album: "Significant Other",
      url: "https://music.youtube.com/watch?v=ZpUYjpKg9KY",
    },
    {
      title: "Boulevard of Broken Dreams",
      artist: "Green Day",
      album: "American Idiot",
      url: "https://music.youtube.com/watch?v=Soa3gO7tL-c",
    },
  ],
  neutral: [
    {
      title: "Bersamamu",
      artist: "Vierra",
      album: "My First Love",
      url: "https://music.youtube.com/watch?v=ASr0z2u8cAU&si=HCZF-jxZhQZ0VEcv",
    },
    {
      title: "Sephia",
      artist: "Sheila On 7",
      album: "Kisah Klasik",
      url: "https://music.youtube.com/watch?v=Y90xQ-bxkWU&si=bjpQov0HA-QrpLae",
    },
    {
      title: "Kangen",
      artist: "Dewa 19",
      album: "Format Masa Depan",
      url: "https://music.youtube.com/watch?v=YKK5_OQiEa4&si=YYmd1NOaub8BIPUU",
    },
    {
      title: "Banana Pancakes",
      artist: "Jack Johnson",
      album: "In Between Dreams",
      url: "https://music.youtube.com/watch?v=6Graa_Vm5eA",
    },
    {
      title: "Better Together",
      artist: "Jack Johnson",
      album: "In Between Dreams",
      url: "https://music.youtube.com/watch?v=u57d4_b_YgI",
    },
    {
      title: "Sunday Morning",
      artist: "Maroon 5",
      album: "Songs About Jane",
      url: "https://music.youtube.com/watch?v=S2Cti12XBw4",
    },
    {
      title: "Gravity",
      artist: "John Mayer",
      album: "Continuum",
      url: "https://music.youtube.com/watch?v=Fo4746w3R5k",
    },
    {
      title: "Put Your Records On",
      artist: "Corinne Bailey Rae",
      album: "Corinne Bailey Rae",
      url: "https://music.youtube.com/watch?v=t0KzLoz-6dU",
    },
    {
      title: "Yellow",
      artist: "Coldplay",
      album: "Parachutes",
      url: "https://music.youtube.com/watch?v=yKNxeF4KMsY",
    },
    {
      title: "Lucky",
      artist: "Jason Mraz ft. Colbie Caillat",
      album: "We Sing. We Dance. We Steal Things.",
      url: "https://music.youtube.com/watch?v=acvIVA9-FMQ",
    },
    {
      title: "Loving You",
      artist: "Seafret",
      album: "Tell Me It's Real",
      url: "https://music.youtube.com/watch?v=q_xFzYl5lEs",
    },
    {
      title: "Photograph",
      artist: "Ed Sheeran",
      album: "x (Multiply)",
      url: "https://music.youtube.com/watch?v=nSDgHBxUbVQ",
    },
    {
      title: "Semua Tentang Kita",
      artist: "Peterpan",
      album: "Taman Langit",
      url: "https://music.youtube.com/watch?v=FdHh4Wfy1ZM",
    },
  ],
  fearful: [
    {
      title: "Bertaut",
      artist: "Nadin Amizah",
      album: "Selamat Ulang Tahun",
      url: "https://music.youtube.com/watch?v=Xh93FL06JwQ&si=zquZsLyKb2uhtgxD",
    },
    {
      title: "Lathi",
      artist: "Weird Genius ft. Sara Fajira",
      album: "Lathi",
      url: "https://music.youtube.com/watch?v=UwTnUpDuwGg&si=nsmI7CL7T_nIqdu0",
    },
    {
      title: "Tanda",
      artist: "Yura Yunita",
      album: "Tanda",
      url: "https://music.youtube.com/watch?v=Q5NBd7CYCCY&si=bOmkBhIrpPFi5zXj",
    },
{
      title: "The Sound of Silence",
      artist: "Disturbed",
      album: "Immortalized",
      url: "https://music.youtube.com/watch?v=u9Dg-g7t2l4",
    },
    {
      title: "Everybody's Got to Learn Sometime",
      artist: "Beck",
      album: "Eternal Sunshine of the Spotless Mind OST",
      url: "https://music.youtube.com/watch?v=vdvWk7JfCOY",
    },
    {
      title: "Crawling",
      artist: "Linkin Park",
      album: "Hybrid Theory",
      url: "https://music.youtube.com/watch?v=Gd9OhYroLN0",
    },
    {
      title: "Breathe Me",
      artist: "Sia",
      album: "Colour the Small One",
      url: "https://music.youtube.com/watch?v=ghPCW2yG3JY",
    },
    {
      title: "Mad World",
      artist: "Gary Jules",
      album: "Trading Snakeoil for Wolftickets",
      url: "https://music.youtube.com/watch?v=4N3N1MlvVc4",
    },
    {
      title: "My Immortal",
      artist: "Evanescence",
      album: "Fallen",
      url: "https://music.youtube.com/watch?v=5anLPw0Efmo",
    },
    {
      title: "Welcome to the Black Parade",
      artist: "My Chemical Romance",
      album: "The Black Parade",
      url: "https://music.youtube.com/watch?v=RRKJiM9Njr8",
    },
    {
      title: "Tear You Apart",
      artist: "She Wants Revenge",
      album: "She Wants Revenge",
      url: "https://music.youtube.com/watch?v=1Rf3Q_wK780",
    },
    {
      title: "House of the Rising Sun",
      artist: "The Animals",
      album: "The Animals",
      url: "https://music.youtube.com/watch?v=0Fy7opKu46c",
    },
    {
      title: "Lullaby",
      artist: "The Cure",
      album: "Disintegration",
      url: "https://music.youtube.com/watch?v=ijxk-fgcg7c",
    },
  ],
  disgusted: [
    {
      title: "Gagal Bersembunyi",
      artist: "The Rain",
      album: "Jabat Erat",
      url: "https://music.youtube.com/watch?v=1h7_0c0IxEs&si=GnwpPrltVvfpX5YM",
    },
    {
      title: "Resah",
      artist: "Payung Teduh",
      album: "Payung Teduh",
      url: "https://music.youtube.com/watch?v=jWq8hHCOJkg&si=uysvoeKjaD1m3aeE",
    },
    {
      title: "You Oughta Know",
      artist: "Alanis Morissette",
      album: "Jagged Little Pill",
      url: "https://music.youtube.com/watch?v=NPcyTyilmYY",
    },
    {
      title: "Gives You Hell",
      artist: "The All-American Rejects",
      album: "When the World Comes Down",
      url: "https://music.youtube.com/watch?v=uxUATkpMQ8A",
    },
    {
      title: "Irreplaceable",
      artist: "Beyoncé",
      album: "B'Day",
      url: "https://music.youtube.com/watch?v=2EwViQxSJJQ",
    },
    {
      title: "Before He Cheats",
      artist: "Carrie Underwood",
      album: "Some Hearts",
      url: "https://music.youtube.com/watch?v=WaSy8yy-mr8",
    },
    {
      title: "Rolling in the Deep",
      artist: "Adele",
      album: "21",
      url: "https://music.youtube.com/watch?v=rYEDA3JcQqw",
    },
    {
      title: "Take a Bow",
      artist: "Rihanna",
      album: "Good Girl Gone Bad: Reloaded",
      url: "https://music.youtube.com/watch?v=J3UjJ4wKLkg",
    },
    {
      title: "FU",
      artist: "Miley Cyrus ft. French Montana",
      album: "Bangerz",
      url: "https://music.youtube.com/watch?v=gkfn5ozZ9SM",
    },
    {
      title: "Sorry Not Sorry",
      artist: "Demi Lovato",
      album: "Tell Me You Love Me",
      url: "https://music.youtube.com/watch?v=-MsvER1dpjM",
    },
    {
      title: "I Hate Everything About You",
      artist: "Three Days Grace",
      album: "Three Days Grace",
      url: "https://music.youtube.com/watch?v=d8ekz_CSBVg",
    },
    {
      title: "Picture to Burn",
      artist: "Taylor Swift",
      album: "Taylor Swift",
      url: "https://music.youtube.com/watch?v=yCMqcFAigRg",
    },
  ],
  surprised: [
    {
      title: "Tiba-Tiba Cinta Datang",
      artist: "Maudy Ayunda",
      album: "Panggil Aku",
      url: "https://music.youtube.com/watch?v=fUPx7OWiXPc&si=-5jCShBOaKcGUva_",
    },
    {
      title: "Lagu Rindu",
      artist: "Kerispatih",
      album: "Kenangan yang Terindah",
      url: "https://music.youtube.com/watch?v=8vL0ZbPaX1g&si=bwtkU3kRAayvDuXS",
    },
    {
      title: "Selamat Ulang Tahun",
      artist: "Jamrud",
      album: "Sydney 090102",
      url: "https://music.youtube.com/watch?v=QJ80jTm4K8I&si=LiQ9h7jo0izVfYFs",
    },
    {
      title: "Resah",
      artist: "Payung Teduh",
      album: "Payung Teduh",
      url: "https://music.youtube.com/watch?v=jWq8hHCOJkg&si=uysvoeKjaD1m3aeE",
    },
    {
      title: "Desember",
      artist: "Efek Rumah Kaca",
      album: "Efek Rumah Kaca",
      url: "https://music.youtube.com/watch?v=qQGVwOTalJw&si=fErYs2YocrAQJaL7",
    },
    {
      title: "Bersamamu",
      artist: "Vierra",
      album: "My First Love",
      url: "https://music.youtube.com/watch?v=ASr0z2u8cAU&si=HCZF-jxZhQZ0VEcv",
    },
        {
      title: "Viva La Vida",
      artist: "Coldplay",
      album: "Viva La Vida or Death and All His Friends",
      url: "https://music.youtube.com/watch?v=dvgZkm1xWPE",
    },
    {
      title: "Bohemian Rhapsody",
      artist: "Queen",
      album: "A Night at the Opera",
      url: "https://music.youtube.com/watch?v=fJ9rUzIMcZQ",
    },
    {
      title: "Some Nights",
      artist: "fun.",
      album: "Some Nights",
      url: "https://music.youtube.com/watch?v=qQkBeOisNM0",
    },
    {
      title: "Feel Good Inc.",
      artist: "Gorillaz",
      album: "Demon Days",
      url: "https://music.youtube.com/watch?v=HyHNuVaZJ-k",
    },
    {
      title: "Electric Feel",
      artist: "MGMT",
      album: "Oracular Spectacular",
      url: "https://music.youtube.com/watch?v=MmZexg8sxyk",
    },
    {
      title: "Surprise Yourself",
      artist: "Jack Garratt",
      album: "Phase",
      url: "https://music.youtube.com/watch?v=3eLfn7Ewx_s",
    },
    {
      title: "Dog Days Are Over",
      artist: "Florence + The Machine",
      album: "Lungs",
      url: "https://music.youtube.com/watch?v=iWOyfLBYtuU",
    },
    {
      title: "Unstoppable",
      artist: "Sia",
      album: "This Is Acting",
      url: "https://music.youtube.com/watch?v=cxjvTXo9WWM",
    },
    {
      title: "Counting Stars",
      artist: "OneRepublic",
      album: "Native",
      url: "https://music.youtube.com/watch?v=hT_nvWreIhg",
    },
    {
      title: "Rude",
      artist: "MAGIC!",
      album: "Don't Kill the Magic",
      url: "https://music.youtube.com/watch?v=PIh2xe4jnpk",
    },
  ],
};